import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  captureRoot: {
    position: 'fixed',
    top: 0,
    left: -20000,
    width: 794,
    zIndex: -1,
    backgroundColor: '#ffffff',
  },
  page: {
    width: 794,
    minHeight: 1123,
    padding: theme.spacing(4.5),
    backgroundColor: '#ffffff',
    color: '#1c2740',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(3),
    boxSizing: 'border-box',
  },
  reportHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(3),
    borderBottom: '1px solid #dbe2f2',
    paddingBottom: theme.spacing(2),
  },
  brandTag: {
    color: '#7d8ba3',
    letterSpacing: '0.24em',
    display: 'block',
    marginBottom: theme.spacing(0.75),
  },
  reportTitle: {
    fontWeight: 700,
    marginBottom: theme.spacing(0.75),
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
  },
  reportSubtitle: {
    color: '#647387',
    lineHeight: 1.6,
    maxWidth: 420,
  },
  metaWrap: {
    minWidth: 220,
    padding: theme.spacing(2),
    borderRadius: 18,
    backgroundColor: '#f4f7ff',
    alignSelf: 'flex-start',
  },
  metaLabel: {
    color: '#7a89a1',
    display: 'block',
    marginBottom: theme.spacing(0.5),
    letterSpacing: '0.12em',
  },
  metaValue: {
    color: '#1c2740',
    fontWeight: 600,
    marginBottom: theme.spacing(1.5),
  },
  statGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
    gap: theme.spacing(2),
  },
  statCard: {
    border: '1px solid #dde4f3',
    borderRadius: 18,
    padding: theme.spacing(2),
    backgroundColor: '#fbfcff',
  },
  statLabel: {
    color: '#7b88a2',
    display: 'block',
    marginBottom: theme.spacing(0.75),
    letterSpacing: '0.1em',
  },
  statValue: {
    color: '#1d2841',
    fontWeight: 700,
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
  },
  chartGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: theme.spacing(2.5),
  },
  chartCard: {
    border: '1px solid #dde4f3',
    borderRadius: 22,
    padding: theme.spacing(2.5),
    backgroundColor: '#fbfcff',
  },
  chartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: theme.spacing(2),
    marginBottom: theme.spacing(2),
  },
  chartTitle: {
    fontWeight: 700,
    color: '#1d2841',
  },
  chartAmount: {
    color: '#6758f3',
    fontWeight: 700,
  },
  chartCanvasWrap: {
    height: 230,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing(2),
  },
  emptyState: {
    width: '100%',
    height: 230,
    borderRadius: 18,
    border: '1px dashed #d4dced',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: theme.spacing(2),
    color: '#6f7d94',
    backgroundColor: '#f7f9ff',
  },
  categoryList: {
    display: 'grid',
    gap: theme.spacing(1),
  },
  categoryRow: {
    display: 'grid',
    gridTemplateColumns: '14px minmax(0, 1fr) auto',
    alignItems: 'center',
    gap: theme.spacing(1),
  },
  swatch: {
    width: 10,
    height: 10,
    borderRadius: '50%',
  },
  categoryName: {
    color: '#2a3952',
  },
  categoryAmount: {
    color: '#647387',
    fontWeight: 600,
  },
  tableCard: {
    border: '1px solid #dde4f3',
    borderRadius: 22,
    padding: theme.spacing(2.5),
    backgroundColor: '#fbfcff',
    flex: 1,
  },
  sectionTitle: {
    color: '#1d2841',
    fontWeight: 700,
    marginBottom: theme.spacing(1.5),
  },
  tableHint: {
    color: '#6f7d94',
    marginBottom: theme.spacing(2),
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  },
  tableHeadCell: {
    textAlign: 'left',
    padding: theme.spacing(1.25, 1.5),
    borderBottom: '1px solid #dbe2f2',
    color: '#7d8ba3',
    fontWeight: 700,
    letterSpacing: '0.08em',
    fontSize: '0.78rem',
  },
  tableCell: {
    padding: theme.spacing(1.35, 1.5),
    borderBottom: '1px solid #eef2fa',
    color: '#2a3952',
    verticalAlign: 'top',
  },
  typePill: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: theme.spacing(0.55, 1.1),
    borderRadius: 999,
    fontSize: '0.78rem',
    fontWeight: 700,
  },
  incomePill: {
    backgroundColor: '#edf2ff',
    color: '#4b56d2',
  },
  expensePill: {
    backgroundColor: '#f1edff',
    color: '#6d56cf',
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: '#7d8ba3',
    fontSize: '0.85rem',
    paddingTop: theme.spacing(1),
    borderTop: '1px solid #dbe2f2',
    marginTop: 'auto',
  },
}));
