import { makeStyles } from '@material-ui/core/styles';

export default makeStyles((theme) => ({
  '@keyframes fadeRise': {
    '0%': { opacity: 0, transform: 'translateY(20px)' },
    '100%': { opacity: 1, transform: 'translateY(0)' },
  },
  '@keyframes floatSoft': {
    '0%': { transform: 'translateY(0px)' },
    '50%': { transform: 'translateY(-10px)' },
    '100%': { transform: 'translateY(0px)' },
  },
  '@keyframes marquee': {
    '0%': { transform: 'translateX(0)' },
    '100%': { transform: 'translateX(-50%)' },
  },
  appShell: {
    position: 'relative',
    minHeight: '100vh',
    overflow: 'hidden',
    padding: theme.spacing(2),
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'stretch',
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(1),
      overflowY: 'auto',
    },
  },
  ambientOrbOne: {
    position: 'absolute',
    top: '-10%',
    left: '-6%',
    width: '28rem',
    height: '28rem',
    borderRadius: '50%',
    background:
      'radial-gradient(circle, rgba(102,126,234,0.16) 0%, rgba(102,126,234,0) 70%)',
    animation: '$floatSoft 10s ease-in-out infinite',
    pointerEvents: 'none',
  },
  ambientOrbTwo: {
    position: 'absolute',
    right: '-6%',
    bottom: '-14%',
    width: '30rem',
    height: '30rem',
    borderRadius: '50%',
    background:
      'radial-gradient(circle, rgba(111,225,214,0.18) 0%, rgba(111,225,214,0) 72%)',
    animation: '$floatSoft 12s ease-in-out infinite reverse',
    pointerEvents: 'none',
  },
  landingScreen: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: 1360,
    height: 'calc(100vh - 32px)',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(2),
    overflow: 'hidden',
    animation: '$fadeRise 650ms ease both',
    [theme.breakpoints.down('md')]: {
      height: 'auto',
      minHeight: 'calc(100vh - 16px)',
      overflow: 'visible',
    },
  },
  landingTopBar: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    alignItems: 'center',
    gap: theme.spacing(2),
    padding: theme.spacing(1.2, 1.6),
    borderRadius: 24,
    background: 'rgba(255,255,255,0.82)',
    border: '1px solid rgba(196, 205, 229, 0.7)',
    boxShadow: '0 18px 50px rgba(63, 75, 115, 0.08)',
    backdropFilter: 'blur(14px)',
    position: 'relative',
    zIndex: 3,
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
      justifyItems: 'stretch',
    },
  },
  topBarBrand: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.2),
  },
  topBarLogo: {
    width: 46,
    height: 46,
    objectFit: 'contain',
  },
  topBarTitle: {
    color: '#182235',
    fontWeight: 700,
    fontFamily: '"Trebuchet MS", "Gill Sans", sans-serif',
  },
  topBarCaption: {
    color: '#66758d',
  },
  topBarButtons: {
    display: 'flex',
    gap: theme.spacing(1),
    justifyContent: 'flex-end',
    [theme.breakpoints.down('md')]: {
      justifyContent: 'flex-start',
    },
  },
  topBarAction: {
    borderRadius: 16,
    textTransform: 'none',
    padding: theme.spacing(1, 2.2),
    color: '#ffffff',
    background: 'linear-gradient(135deg, #6b73ff 0%, #6758f3 100%)',
    boxShadow: '0 14px 30px rgba(103, 88, 243, 0.24)',
    fontWeight: 700,
    '&:hover': {
      background: 'linear-gradient(135deg, #7580ff 0%, #6f60f5 100%)',
    },
  },
  landingHero: {
    flex: 1,
    minHeight: 0,
    display: 'grid',
    gridTemplateColumns: '0.95fr 1.05fr',
    gap: theme.spacing(2),
    alignItems: 'stretch',
    marginTop: theme.spacing(0.5),
    position: 'relative',
    zIndex: 1,
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
      flex: 'none',
      marginTop: 0,
    },
  },
  landingCopy: {
    minHeight: 0,
    padding: theme.spacing(3.3, 3.4),
    borderRadius: 34,
    background:
      'linear-gradient(180deg, rgba(255,255,255,0.92) 0%, rgba(244,248,255,0.88) 100%)',
    border: '1px solid rgba(200, 208, 230, 0.72)',
    boxShadow: '0 24px 70px rgba(78, 91, 136, 0.08)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    overflow: 'hidden',
    position: 'relative',
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(3, 2.4),
      borderRadius: 26,
    },
  },
  motionStrip: {
    width: '100%',
    overflow: 'hidden',
    borderRadius: 999,
    marginBottom: theme.spacing(1.2),
    minHeight: 46,
    padding: theme.spacing(0.72, 0),
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(238, 242, 255, 0.9)',
    border: '1px solid rgba(202, 210, 236, 0.8)',
  },
  motionTrack: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(2.5),
    width: 'max-content',
    animation: '$marquee 20s linear infinite',
    '& span': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: theme.spacing(0.8),
      color: '#58667d',
      fontSize: '0.92rem',
      fontWeight: 700,
      lineHeight: 1.15,
      whiteSpace: 'nowrap',
      '&:before': {
        content: '""',
        width: 7,
        height: 7,
        borderRadius: '50%',
        display: 'inline-block',
        backgroundColor: '#6b73ff',
      },
    },
  },
  kicker: {
    color: '#7b88a2',
    letterSpacing: '0.28em',
    display: 'block',
    marginBottom: theme.spacing(0.9),
  },
  heroTitle: {
    fontSize: 'clamp(2.6rem, 4.6vw, 4.6rem)',
    lineHeight: 0.96,
    color: '#172238',
    fontWeight: 700,
    marginBottom: theme.spacing(1.1),
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
  },
  heroSubtitle: {
    color: '#58667d',
    lineHeight: 1.45,
    fontWeight: 600,
    marginBottom: theme.spacing(1),
    maxWidth: 620,
    [theme.breakpoints.down('sm')]: {
      fontSize: '1.08rem',
    },
  },
  heroDescription: {
    color: '#647387',
    maxWidth: 620,
    fontSize: '0.97rem',
    lineHeight: 1.6,
    marginBottom: theme.spacing(1.5),
  },
  highlightRow: {
    display: 'grid',
    gap: theme.spacing(1),
    marginBottom: theme.spacing(1.6),
    maxWidth: 420,
  },
  highlightPill: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    padding: theme.spacing(0.75, 1),
    borderRadius: 16,
    backgroundColor: 'rgba(249, 251, 255, 0.95)',
    border: '1px solid rgba(206, 214, 236, 0.85)',
    color: '#31415a',
    fontSize: '0.9rem',
    fontWeight: 700,
  },
  highlightIcon: {
    color: '#6b73ff',
    fontSize: '1.1rem',
  },
  heroActions: {
    display: 'flex',
    gap: theme.spacing(1.4),
    flexWrap: 'wrap',
  },
  primaryAction: {
    padding: theme.spacing(1.3, 2.8),
    borderRadius: 18,
    background: 'linear-gradient(135deg, #6b73ff 0%, #6758f3 100%)',
    color: '#ffffff',
    boxShadow: '0 16px 34px rgba(103, 88, 243, 0.24)',
    textTransform: 'none',
    fontSize: '1rem',
    fontWeight: 700,
    '&:hover': {
      background: 'linear-gradient(135deg, #7780ff 0%, #705ff4 100%)',
    },
  },
  landingSide: {
    minHeight: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing(0.6, 0),
    [theme.breakpoints.down('md')]: {
      minHeight: 'auto',
      padding: 0,
    },
  },
  landingPreview: {
    width: '100%',
    maxWidth: 560,
    minHeight: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  previewCard: {
    width: '100%',
    maxWidth: 500,
    padding: theme.spacing(2.5),
    borderRadius: 28,
    background: 'rgba(255,255,255,0.9)',
    border: '1px solid rgba(201, 209, 233, 0.82)',
    boxShadow: '0 30px 70px rgba(66, 82, 128, 0.12)',
    animation: '$fadeRise 820ms ease both',
    position: 'relative',
    zIndex: 2,
  },
  previewWindowBar: {
    display: 'flex',
    gap: theme.spacing(0.75),
    marginBottom: theme.spacing(2),
    '& span': {
      width: 10,
      height: 10,
      borderRadius: '50%',
      backgroundColor: '#c6d0eb',
    },
  },
  previewHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: theme.spacing(1.2),
    marginBottom: theme.spacing(1.2),
  },
  previewEyebrow: {
    color: '#7c8aa3',
    letterSpacing: '0.16em',
    display: 'block',
    marginBottom: theme.spacing(0.45),
  },
  previewTitle: {
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
    fontSize: '1.8rem',
    lineHeight: 1.2,
    color: '#1c2740',
  },
  previewBadge: {
    padding: theme.spacing(0.6, 1.1),
    borderRadius: 999,
    background: 'rgba(103, 88, 243, 0.1)',
    color: '#6758f3',
    fontWeight: 700,
    fontSize: '0.82rem',
    whiteSpace: 'nowrap',
  },
  previewText: {
    color: '#627289',
    lineHeight: 1.7,
    marginBottom: theme.spacing(1.8),
  },
  previewSummaryCard: {
    padding: theme.spacing(2),
    borderRadius: 22,
    background:
      'linear-gradient(135deg, rgba(107,115,255,0.08) 0%, rgba(111,225,214,0.1) 100%)',
    border: '1px solid rgba(201, 210, 236, 0.95)',
    marginBottom: theme.spacing(1.5),
  },
  summaryTag: {
    color: '#7d8ba3',
    letterSpacing: '0.14em',
    display: 'block',
    marginBottom: theme.spacing(0.7),
  },
  summaryValue: {
    color: '#1d2740',
    fontWeight: 700,
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
    marginBottom: theme.spacing(0.6),
  },
  summaryCopy: {
    color: '#647387',
    lineHeight: 1.6,
  },
  previewLedger: {
    display: 'grid',
    gap: theme.spacing(0.9),
    marginBottom: theme.spacing(1.6),
  },
  ledgerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    padding: theme.spacing(1, 1.2),
    borderRadius: 16,
    backgroundColor: 'rgba(247, 249, 255, 0.95)',
    border: '1px solid rgba(208, 215, 236, 0.85)',
    color: '#53637b',
    '& strong': {
      color: '#1f2a42',
    },
  },
  previewFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: theme.spacing(1),
    color: '#6f7e95',
    fontSize: '0.85rem',
    fontWeight: 700,
    flexWrap: 'wrap',
  },
  dashboardScreen: {
    position: 'relative',
    zIndex: 1,
    width: '100%',
    maxWidth: 1360,
    minHeight: 'calc(100vh - 32px)',
    padding: theme.spacing(3),
    borderRadius: 34,
    background:
      'linear-gradient(180deg, rgba(255,255,255,0.88) 0%, rgba(242,246,255,0.9) 100%)',
    boxShadow: '0 26px 80px rgba(63, 75, 115, 0.1)',
    border: '1px solid rgba(198, 207, 230, 0.74)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    animation: '$fadeRise 650ms ease both',
    [theme.breakpoints.down('sm')]: {
      minHeight: 'calc(100vh - 16px)',
      padding: theme.spacing(2),
      borderRadius: 24,
    },
  },
  dashboardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: theme.spacing(2),
    marginBottom: theme.spacing(3),
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column',
    },
  },
  dashboardBrand: {
    marginBottom: theme.spacing(1),
  },
  dashboardBrandLogo: {
    width: 54,
    height: 54,
    objectFit: 'contain',
  },
  dashboardKicker: {
    color: '#7b88a2',
    letterSpacing: '0.24em',
    display: 'block',
    marginBottom: theme.spacing(0.7),
  },
  dashboardTitle: {
    color: '#19253a',
    fontFamily: '"Palatino Linotype", "Book Antiqua", Garamond, serif',
    marginBottom: theme.spacing(1),
    [theme.breakpoints.down('sm')]: {
      fontSize: '2rem',
    },
  },
  dashboardSubtitle: {
    color: '#647387',
    maxWidth: 620,
    lineHeight: 1.7,
  },
  secondaryAction: {
    borderRadius: 16,
    textTransform: 'none',
    color: '#33405b',
    borderColor: 'rgba(184, 194, 220, 0.95)',
    padding: theme.spacing(1.1, 1.8),
    fontWeight: 700,
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: '310px minmax(0, 1fr)',
    gap: theme.spacing(3),
    flex: 1,
    minHeight: 0,
    [theme.breakpoints.down('md')]: {
      gridTemplateColumns: '1fr',
      overflowY: 'auto',
    },
  },
  summaryRail: {
    display: 'grid',
    gap: theme.spacing(2),
    minHeight: 0,
  },
  workspacePanel: {
    minHeight: 0,
    display: 'flex',
  },
}));
